[project]
name = 'fitness-rewards'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fitness-rewards]
path = 'contracts/fitness-rewards.clar'
clarity_version = 3
epoch = 3.0

[contracts.goals]
path = 'contracts/goals.clar'
clarity_version = 3
epoch = 3.0

[contracts.ownable_traits]
path = 'contracts/ownable.clar'
clarity_version = 3
epoch = 3.0

[contracts.proofs]
path = 'contracts/proofs.clar'
clarity_version = 3
epoch = 3.0

[contracts.rewards]
path = 'contracts/rewards.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
